name: CI
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2019

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_TARGET_TRIPLET: "x64-windows"

    steps:
      - uses: actions/checkout@v4

      - name: Export Github Cache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Setup vcpkg
        id: vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "vcpkg.json"

      - name: Configure
        run: cmake --preset win-release

      - name: Build
        run: cmake --build --preset build-release

      - name: Run Integration Test
        shell: cmd
        run: |
          copy raw_iq_samples.bin build\Release\
          cd build\Release
          .\DSPPipelineTest.exe